name: kiss_firebase_datastore
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/WAMF/kiss_firebase_datastore

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  kiss_datastore: ^0.1.0
  firebase_core: ^1.19.0
  firebase_storage: ^10.3.11


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
